(local Harness (require :tests.e2e.harness))
(local ButtonTest (require :tests.e2e.test-button))
(local ButtonStatesTest (require :tests.e2e.test-button-states))
(local ImageTest (require :tests.e2e.test-image))
(local QrCodeViewTest (require :tests.e2e.test-qr-code-view))
(local VideoTest (require :tests.e2e.test-video))
(local HudButtonTest (require :tests.e2e.test-hud-button))
(local LauncherViewTest (require :tests.e2e.test-launcher-view))
(local SceneButtonTest (require :tests.e2e.test-scene-button))
(local SceneHudButtonTest (require :tests.e2e.test-scene-hud-button))
(local SceneCubeFacesTest (require :tests.e2e.test-scene-cube-faces))
(local ScrollViewTest (require :tests.e2e.test-scroll-view))
(local ScrollViewTopTest (require :tests.e2e.test-scroll-view-top))
(local ListViewTest (require :tests.e2e.test-list-view))
(local ListViewExtraSpaceTest (require :tests.e2e.test-list-view-extra-space))
(local LlmMessageDialogTest (require :tests.e2e.test-llm-message-dialog))
(local LlmConversationDialogTest (require :tests.e2e.test-llm-conversation-dialog))
(local LlmChatViewTest (require :tests.e2e.test-llm-chat-view))
(local ComboBoxTest (require :tests.e2e.test-combo-box))
(local RenderCaptureTest (require :tests.e2e.test-render-capture))
(local ThemeSnapshotTest (require :tests.e2e.test-theme-snapshot))
(local GraphNodePointsTest (require :tests.e2e.test-graph-node-points))
(local GraphEdgesTest (require :tests.e2e.test-graph-edges))
(local HudFloatResizeTest (require :tests.e2e.test-hud-float-resize))
(local HudFloatResizeDirectTest (require :tests.e2e.test-hud-float-resize-direct))
(local HudDepthOrderingTest (require :tests.e2e.test-hud-depth-ordering))
(local DrawingWorkflowTest (require :tests.e2e.test-drawing-workflow))
(local XdgIconBrowserTest (require :tests.e2e.test-xdg-icon-browser))
(local StringEntityViewTest (require :tests.e2e.test-string-entity-view))
(local LinkEntityViewTest (require :tests.e2e.test-link-entity-view))
(local ListEntityViewTest (require :tests.e2e.test-list-entity-view))
(local NotebookViewTest (require :tests.e2e.test-notebook-view))
(local TabViewTest (require :tests.e2e.test-tab-view))
(local SubAppTest (require :tests.e2e.test-sub-app))
(local TetrisDeepDialogTest (require :tests.e2e.test-tetris-deep-dialog))
(local LightingTest (require :tests.e2e.test-lighting))
(local InputCursorAlignmentTest (require :tests.e2e.test-input-cursor-alignment))
(local InputVirtualInputCaretParityTest (require :tests.e2e.test-input-virtual-input-caret-parity))
(local TerminalRendererTransformTest (require :tests.e2e.test-terminal-renderer-transform))
(local HoverRectLifecycleTest (require :tests.e2e.test-hover-rect-lifecycle))
(local RenderSmokeTest (require :tests.e2e.test-render-smoke))
(local FsFileViewerVirtualInputTest (require :tests.e2e.test-fs-file-viewer-virtual-input))

(fn run-all []
  (ButtonTest.main)
  (ButtonStatesTest.main)
  (ImageTest.main)
  (QrCodeViewTest.main)
  (VideoTest.main)
  (ScrollViewTest.main)
  (ScrollViewTopTest.main)
  (ListViewTest.main)
  (ListViewExtraSpaceTest.main)
  (LlmMessageDialogTest.main)
  (LlmConversationDialogTest.main)
  (LlmChatViewTest.main)
  (ComboBoxTest.main)
  (ThemeSnapshotTest.main)
  (GraphNodePointsTest.main)
  (GraphEdgesTest.main)
  (HudButtonTest.main)
  (LauncherViewTest.main)
  (HudFloatResizeTest.main)
  (HudFloatResizeDirectTest.main)
  (HudDepthOrderingTest.main)
  (DrawingWorkflowTest.main)
  (SceneButtonTest.main)
  (SceneHudButtonTest.main)
  (SceneCubeFacesTest.main)
  (XdgIconBrowserTest.main)
  (StringEntityViewTest.main)
  (LinkEntityViewTest.main)
  (ListEntityViewTest.main)
  (NotebookViewTest.main)
  (TabViewTest.main)
  (SubAppTest.main)
  (TetrisDeepDialogTest.main)
  (LightingTest.main)
  (InputCursorAlignmentTest.main)
  (InputVirtualInputCaretParityTest.main)
  (TerminalRendererTransformTest.main)
  (HoverRectLifecycleTest.main)
  (RenderSmokeTest.main)
  (FsFileViewerVirtualInputTest.main)
  (RenderCaptureTest.main))

(fn main []
  (run-all)
  (print "E2E snapshots complete"))

{:main main}
