name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  bundle:
    uses: semanticdreams/space2/.github/workflows/bundle.yml@v1
    with:
      space-version: v1.2.3
      app-name: Snake
      app-id: snake
